/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    App: typeof import('./../App.vue')['default']
    CommonAside: typeof import('./../Layout/CommonAside.vue')['default']
    CommonHeader: typeof import('./../Layout/CommonHeader.vue')['default']
    CommonLayout: typeof import('./../Layout/CommonLayout.vue')['default']
    ComponentsCommonAside: typeof import('./../Layout/components/CommonAside.vue')['default']
    ComponentsCommonHeader: typeof import('./../Layout/components/CommonHeader.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElMenuItemGroup: typeof import('element-plus/es')['ElMenuItemGroup']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    IEpExpand: typeof import('~icons/ep/expand')['default']
    IEpFold: typeof import('~icons/ep/fold')['default']
    Layout: typeof import('./../Layout/index.vue')['default']
    LayoutCommonAside: typeof import('./../components/Layout/CommonAside.vue')['default']
    LayoutCommonHeader: typeof import('./../components/Layout/CommonHeader.vue')['default']
    LayoutCommonLayout: typeof import('./../components/Layout/CommonLayout.vue')['default']
    LayoutComponentsCommonAside: typeof import('./../Layout/components/CommonAside.vue')['default']
    LayoutComponentsCommonHeader: typeof import('./../Layout/components/CommonHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
  }
}
